# https://www.weave.works/blog/labels-in-prometheus-alerts-think-twice-before-using-them
route:
 #group_by: [cluster]
 group_by: ['alertname', 'instance', 'type']
 group_wait: 30s
 group_interval: 5m
 repeat_interval: 5m
 # If an alert isn't caught by a route, send emails (default)
 receiver: email_alerts
 routes:
  # Send severity=slack alerts to slack.
  - match:
      severity: page
    continue: true
    receiver: email_alerts
  - match:
      severity: page
    continue: true
    receiver: slack_alerts
  - match:
      severity: page
    continue: true
    receiver: team1_alerts
  - match:
      severity: page
    continue: true
    receiver: team2_alerts

receivers:
- name: email_alerts
  email_configs:
  - to: 'team1@noneck.io, team2@noneck.io'
    from: it_notification@noneck.io
    smarthost: 10.66.6.25:25
    send_resolved: true
    require_tls: false
- name: slack_alerts
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/${DEFAULT_SLACK_TOKEN}'
    username: 'Prometheus'
    channel: '#alerts'
    send_resolved: true
    title: '{{ template "slack.my.title" . }}'
    text: '{{ template "slack.my.text" . }}'
- name: team1_alerts
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/${TEAM1_SLACK_TOKEN}'
    username: 'Prometheus'
    channel: '#alerts'
    send_resolved: true
    title: '{{ template "slack.my.title" . }}'
    text: '{{ template "slack.my.text" . }}'
  pushover_configs:
  - token: ${team1_pushover_token}
    user_key: ${team2_pushover_key}
    send_resolved: true
- name: team2_alerts
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/${TEAM2_SLACK_TOKEN}'
    username: 'Prometheus'
    channel: '#alerts'
    send_resolved: true
    title: '{{ template "slack.my.title" . }}'
    text: '{{ template "slack.my.text" . }}'
  pushover_configs:
  - token: ${team2_pushover_token}
    user_key: ${team2_pushover_key}
    send_resolved: true

templates:
- '/etc/alertmanager/templates/slack.tmpl'
