# https://www.weave.works/blog/labels-in-prometheus-alerts-think-twice-before-using-them
#templates:
#- '/etc/alertmanager/template/*.tmpl'
global:
  slack_api_url: '<slack_webhook_url>'
route:
 #group_by: [cluster]
 group_by: ['alertname', 'instance', 'type']
 group_wait: 30s
 group_interval: 5m
 repeat_interval: 5m
 # If an alert isn't caught by a route, send it slack.
 receiver: slack_general
 routes:
  # Send severity=slack alerts to slack.
  - match:
      severity: slack
    receiver: slack_general

receivers:
- name: slack_general
  slack_configs:
  - username: 'Prometheus'
    channel: '#alerts'
    send_resolved: true
    title: '{{ template "slack.my.title" . }}'
    text: '{{ template "slack.my.text" . }}'

templates:
- '/etc/alertmanager/templates/slack.tmpl'
