global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'host'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
        - targets: ['prometheus:9090']

  - job_name: 'blackbox'
    scrape_interval: 30s
    static_configs:
        - targets: ['blackbox:9115']

  - job_name: 'alertmanager'
    scrape_interval: 30s
    static_configs:
        - targets: ['alertmanager:9093']

  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
        - targets: [ 'cadvisor:8080']

  - job_name: 'nodeexporter'
    scrape_interval: 30s
    static_configs:
        - targets: ['nodeexporter:9100']

  - job_name: 'grafana'
    scrape_interval: 30s
    static_configs:
        - targets: ['grafana:3000']

  - job_name: 'Servers'
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 8s
    static_configs:
        - targets: ['10.66.6.110:9182']
          labels:
            hostname: 'watson'
            service: 'utility'
        - targets: ['10.66.6.4:9182']
          labels:
            hostname: 'curdz'
            service: 'WSUS'
        - targets: ['10.66.6.201:9182']
          labels:
            hostname: 'odin'
            service: 'Domain Controller'
        - targets: ['10.66.6.20:9182']
          labels:
            hostname: 'warez'
            service: 'File & Printer Sharing'
        - targets: ['10.66.6.21:9182']
          labels:
            hostname: 'deebz'
            service: 'MariaDB'

  - job_name: noneck.io
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
     - targets:
        - http://www.noneck.io/
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: blackbox:9115 # The blackbox exporter.

  - job_name: WSUS
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
     - targets:
        - http://10.66.6.4:8530/
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: blackbox:9115 # The blackbox exporter.

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

